"""
Weapon build data from wzhub.gg — complete Warzone Season 3 dataset (May 2026).
Covers all tiers: Absolute Meta, Meta, Acceptable (A), Unrated (B).
"""

import requests

WZHUB_URL = "https://wzhub.gg/loadouts"

WARZONE_BUILDS = [
    # ══════════════════════════════════════════════════════
    # ABSOLUTE META
    # ══════════════════════════════════════════════════════
    {"weapon_name":"Voyak KT-3","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"Absolute Meta","confidence":0.97,
     "attachments":["Optic: Fang Hoverpoint ELO","Muzzle: Monolithic Suppressor","Barrel: 17.6\" LTI Grav-4 Barrel","Magazine: SK-Garrison Drum","Stock: V-Last Control Pad"],
     "reasoning":"Season 3 top AR. Dominates long range with best-in-class recoil control and bullet velocity."},
    {"weapon_name":"VST","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"Absolute Meta","confidence":0.96,
     "attachments":["Muzzle: Hawker Series 45","Barrel: 14\" LTI Expedition Barrel","Magazine: Avarice Extended Mag II","Stock: Hawker Cub-55 Pad","Fire Mods: Buffer Springs"],
     "reasoning":"Best close-range SMG. Fastest TTK under 15m with manageable recoil."},
    {"weapon_name":"DS20 Mirage","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"Absolute Meta","confidence":0.95,
     "attachments":["Optic: Greaves Accuspot 3X","Muzzle: Monolithic Suppressor","Barrel: 17.1\" Abdicator Barrel","Magazine: Griffon Reserve Extended II","Fire Mods: Recoil Sync Unit"],
     "reasoning":"Laser-beam AR at range. Recoil Sync Unit makes it one of the easiest guns to control."},
    {"weapon_name":"Strider 300","weapon_class":"Sniper","game":"Warzone","play_style":"Sniper","tier":"Absolute Meta","confidence":0.95,
     "attachments":["Muzzle: Monolithic Suppressor","Barrel: 25\" Bowen Grooved Barrel","Underbarrel: Cornerstone-642 Guard","Rear Grip: Hatch Quick Grip","Fire Mods: .300 WM Overpressured"],
     "reasoning":"Dominant sniper. One-shot potential at all ranges with excellent bullet velocity."},
    # ══════════════════════════════════════════════════════
    # META
    # ══════════════════════════════════════════════════════
    {"weapon_name":"MK.78","weapon_class":"LMG","game":"Warzone","play_style":"Long Range","tier":"Meta","confidence":0.92,
     "attachments":["Optic: Greaves Accuspot 3X","Muzzle: RL-7.62 Compensator","Barrel: 25\" EAM Heavy Barrel","Underbarrel: Bowen Sentry Foregrip","Fire Mods: Accelerated Recoil System"],
     "reasoning":"Highest pick-rate weapon (24.9%). Insane damage at range with forgiving recoil."},
    {"weapon_name":"Razor 9mm","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"Meta","confidence":0.90,
     "attachments":["Optic: Lethal Tools ELO","Muzzle: H-9MM Precision Comp","Barrel: 12\" MFS Sidewinder Barrel","Magazine: Zealot Extended Mag II","Fire Mods: Accelerated Recoil System"],
     "reasoning":"Top-tier SMG alternative to VST. Slightly more forgiving with better bullet spread."},
    {"weapon_name":"Dravec 45","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"Meta","confidence":0.88,
     "attachments":["Muzzle: Hawker Series 45","Barrel: 19\" EAM Horizon Barrel","Magazine: Gator Extended Mag","Laser: MFS Agile Laser Pro","Fire Mods: Bolt Carrier Group"],
     "reasoning":"Excellent all-rounder SMG. Easy to use for any skill level."},
    {"weapon_name":"EGRT-17","weapon_class":"AR","game":"Warzone","play_style":"Support","tier":"Meta","confidence":0.88,
     "attachments":["Optic: Greaves Accuspot 3X","Muzzle: EAM Finset Brake","Barrel: 16.5\" Bowen Resistor Barrel","Magazine: Fuel Cell-X3 Mag","Stock: Frigate Control Stock"],
     "reasoning":"Versatile AR that works as sniper support. Excellent mid-range TTK."},
    {"weapon_name":"Sturmwolf 45","weapon_class":"SMG","game":"Warzone","play_style":"Aggressive","tier":"Meta","confidence":0.87,
     "attachments":["Barrel: 14.8\" Perigee Barrel","Underbarrel: Envoy Foregrip","Magazine: B-45 Roar Drum","Rear Grip: Selene Rover Grip","Stock: Itinerant Light Stock"],
     "reasoning":"Extremely fast movement speed. Built for aggressive rushing and close-quarter dominance."},
    {"weapon_name":"MK35 ISR","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"Meta","confidence":0.87,
     "attachments":["Optic: Fang Hoverpoint ELO","Muzzle: Monolithic Suppressor","Barrel: 16.5\" Greaves Bellum Barrel","Magazine: Bowen Siren Drum","Fire Mods: 5.56 NATO FMJ"],
     "reasoning":"Consistent at range. FMJ ammo makes it strong through cover."},
    {"weapon_name":"Hawker HX","weapon_class":"Sniper","game":"Warzone","play_style":"Sniper","tier":"Meta","confidence":0.86,
     "attachments":["Muzzle: Monolithic Suppressor","Barrel: 27.4\" Teleos Range Barrel","Magazine: Amrita Fast Mag","Rear Grip: Auroral Light Grip","Fire Mods: .338 LM Overpressured"],
     "reasoning":"Fast bolt-action alternative to Strider. Faster rechamber with slightly less velocity."},
    {"weapon_name":"Kogot-7","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"Meta","confidence":0.86,
     "attachments":["Muzzle: Hawker Series 45","Barrel: 13.5\" Canis-05 Barrel","Underbarrel: VAS Drift Lock Foregrip","Magazine: Vex Expanse Mag","Fire Mods: Buffer Spring"],
     "reasoning":"Compact SMG with top-tier hipfire. Great for indoors and tight rotations."},
    {"weapon_name":"VS Recon","weapon_class":"Sniper","game":"Warzone","play_style":"Sniper","tier":"Meta","confidence":0.85,
     "attachments":["Muzzle: Monolithic Suppressor","Barrel: 23\" G-Force Barrel","Underbarrel: Stetig-C Handguard","Rear Grip: R-1 Shelf Grip","Fire Mods: 7.62 NATO Overpressured"],
     "reasoning":"Semi-auto sniper. Great when you need follow-up shots quickly."},
    # ══════════════════════════════════════════════════════
    # A TIER (Acceptable)
    # ══════════════════════════════════════════════════════
    {"weapon_name":"SG-12","weapon_class":"Shotgun","game":"Warzone","play_style":"Close Range","tier":"A","confidence":0.77,
     "attachments":["Muzzle: Breacher Onyx Brake","Barrel: 20\" Hawker Reach Barrel","Underbarrel: Redwell Dash Handstop","Magazine: Bowen Bighorn Drum","Laser: Convergence Box Laser"],
     "reasoning":"Best shotgun in the meta. Dangerous within 5m."},
    {"weapon_name":"MXR-17","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.78,
     "attachments":["Optic: Lethal Tools ELO","Muzzle: Monolithic Suppressor","Barrel: 17\" Greaves Scourge Barrel","Underbarrel: Lateral Precision Grip","Magazine: Rhodes Drum Mag"],
     "reasoning":"Solid long-range AR. Slightly outclassed by Voyak but very accessible."},
    {"weapon_name":"Carbon 57","weapon_class":"SMG","game":"Warzone","play_style":"Aggressive","tier":"A","confidence":0.76,
     "attachments":["Muzzle: K&S Compensator","Barrel: 14\" Rockleigh Barrel","Underbarrel: Sapper Guard Handstop","Rear Grip: Dulcet Control Grip","Fire Mods: Accelerated Recoil System"],
     "reasoning":"High pick-rate aggressive SMG. Shines in teams that push hard."},
    {"weapon_name":"AK-27","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.76,
     "attachments":["Optic: Lethal Tools ELO","Muzzle: Monolithic Suppressor","Barrel: 17.6\" Vandal Heavy Barrel","Underbarrel: Lateral Precision Grip","Magazine: Saber Pack Heavy Drum"],
     "reasoning":"High damage AR with excellent bullet penetration."},
    {"weapon_name":"XR-3 Ion","weapon_class":"Sniper","game":"Warzone","play_style":"Sniper","tier":"A","confidence":0.75,
     "attachments":["Optic: Greaves Accuspot 3X","Muzzle: LTI Triad Suppressor","Barrel: 20\" Ion Trinity Barrel","Underbarrel: Zero-S Handguard","Fire Mods: 7.62 NATO Overpressured"],
     "reasoning":"Anti-materiel sniper. High-risk, high-reward for experienced snipers."},
    {"weapon_name":"Maddox RFB","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.74,
     "attachments":["Optic: Greaves Accuspot 3X","Muzzle: Monolithic Suppressor","Barrel: 19\" Virtuous-OP Barrel","Magazine: Billing Extended Mag","Stock: Furrow Control Stock"],
     "reasoning":"Legacy BO6 AR still competitive. Great for players who know it well."},
    {"weapon_name":"Sokol 545","weapon_class":"LMG","game":"Warzone","play_style":"Support","tier":"A","confidence":0.73,
     "attachments":["Optic: Greaves Accuspot 3X","Muzzle: Monolithic Suppressor","Barrel: 18.2\" Parlous Heavy Barrel","Stock: Taction Control Stock","Fire Mods: Buffer Spring"],
     "reasoning":"Reliable suppression LMG. Lower mobility than MK.78 but very stable."},
    {"weapon_name":"Jackal PDW","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"A","confidence":0.72,
     "attachments":["Muzzle: Compensator","Barrel: Long Barrel","Underbarrel: Vertical Foregrip","Magazine: Extended Mag II","Rear Grip: Ergonomic Grip"],
     "reasoning":"Workhorse SMG with no real weakness. Not flashy but consistently solid."},
    {"weapon_name":"MPC-25","weapon_class":"SMG","game":"Warzone","play_style":"Hip Fire","tier":"A","confidence":0.72,
     "attachments":["Muzzle: K&S Compensator","Underbarrel: Zero Shift Handstop","Magazine: MPC Overload Drum","Rear Grip: Magnate Grip","Fire Mods: Recoil Sync Unit"],
     "reasoning":"Best hipfire SMG in the meta. Devastating in tight spaces."},
    {"weapon_name":"Grekhova","weapon_class":"Pistol","game":"Warzone","play_style":"Close Range","tier":"A","confidence":0.71,
     "attachments":["Muzzle: Monolithic Suppressor","Barrel: Reinforced Barrel","Magazine: Extended Mag III","Rear Grip: Quickdraw Grip","Fire Mods: Rapid Fire"],
     "reasoning":"Best secondary in WZ. Rapid fire mode makes it a CQB weapon in its own right."},
    {"weapon_name":"REV-46","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"A","confidence":0.70,
     "attachments":["Optic: Lethal Tools ELO","Muzzle: Hawker Series 45","Barrel: Caudal Target Barrel","Magazine: Cawdor Extended Mag","Fire Mods: Recoil Sync Unit"],
     "reasoning":"Underrated SMG with above-average range for its class."},
    {"weapon_name":"M8A1","weapon_class":"Marksman","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.70,
     "attachments":["Optic: Greaves Accuspot 3X","Muzzle: Monolithic Suppressor","Barrel: M8A1 Autostrike-X8 Conversion","Magazine: Redline Capacity Drum","Stock: Gridlock Stock"],
     "reasoning":"BO7 battle rifle with conversion kit. High damage per shot makes it viable at any range."},
    {"weapon_name":"M15 Mod 0","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.69,
     "attachments":["Optic: Lethal Tools ELO","Muzzle: Monolithic Suppressor","Barrel: 16\" Reticulated Barrel","Magazine: Bowen Bulwark Mag","Rear Grip: Caravan-H2 Grip"],
     "reasoning":"Steady AR with good range. Slightly less damage than top-tier ARs."},
    {"weapon_name":"SAUG","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"A","confidence":0.68,
     "attachments":["Muzzle: Compensator","Underbarrel: Vertical Foregrip","Magazine: Extended Mag II","Rear Grip: Commando Grip","Stock: Light Stock"],
     "reasoning":"Classic BO1 SMG back in the loot pool. Still holds its own at close range."},
    {"weapon_name":"MX9","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"A","confidence":0.68,
     "attachments":["Optic: Slate Reflector","Muzzle: XRK Sandstorm","Barrel: 16.5\" Bruen S901","Magazine: Extended Mag","Rear Grip: Bruen Q900 Grip"],
     "reasoning":"Snappy SMG that's easy to learn. Good entry point for SMG players."},
    {"weapon_name":"Victus XMR","weapon_class":"Sniper","game":"Warzone","play_style":"Sniper","tier":"A","confidence":0.68,
     "attachments":["Optic: SP-X 80 6.6X","Muzzle: VT-7 Spiritfire Suppressor XL","Barrel: Mack 8 33.5 Super","Stock: XRK Rise 50","Ammunition: .50 Cal High Velocity"],
     "reasoning":"Legacy MW2 sniper. One-shot potential but slower than BO7 alternatives."},
    {"weapon_name":"KAR98K","weapon_class":"Sniper","game":"Warzone","play_style":"Sniper","tier":"A","confidence":0.68,
     "attachments":["Optic: SP-X 80 6.6X","Muzzle: Sonic Suppressor L","Barrel: Präzisionsgewehr 762 Long Barrel","Laser: SL Razorhawk Laser Light","Ammunition: 7.92 High Grain Rounds"],
     "reasoning":"Fastest ADS sniper in the game. High-skill ceiling but rewarding for aggressive snipers."},
    {"weapon_name":"Superi 46","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"A","confidence":0.67,
     "attachments":["Muzzle: Shadowstrike Suppressor S","Barrel: Bore 99 Short Barrel","Underbarrel: JAK Slash","Magazine: 40 Round Mag","Stock: Rescue-9 Stock"],
     "reasoning":"Niche SMG with good hipfire. Works well in ultra-close environments."},
    {"weapon_name":"Ladra","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"A","confidence":0.67,
     "attachments":["Muzzle: Compensator","Barrel: Reinforced Barrel","Underbarrel: Ranger Foregrip","Magazine: Extended Mag I","Stock: Balanced Stock"],
     "reasoning":"Lightweight SMG with balanced stats. Good all-arounder for casual play."},
    {"weapon_name":"FFAR 1","weapon_class":"AR","game":"Warzone","play_style":"Aggressive","tier":"A","confidence":0.67,
     "attachments":["Optic: Volzhskiy Reflex","Muzzle: Compensator","Barrel: Gain-Twist Barrel","Underbarrel: Vertical Foregrip","Magazine: Extended Mag II"],
     "reasoning":"Fast-firing AR. Shines in aggressive close-mid range where other ARs falter."},
    {"weapon_name":"XM4","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.67,
     "attachments":["Optic: Jason Armory 2X","Barrel: Gain-Twist Barrel","Underbarrel: Vertical Foregrip","Magazine: Extended Mag III","Stock: Buffer Weight Stock"],
     "reasoning":"Classic BO6 AR with consistent performance. Easy recoil management."},
    {"weapon_name":"Kilo 141","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.66,
     "attachments":["Optic: Willis 3X","Muzzle: Monolithic Suppressor","Barrel: Reinforced Barrel","Underbarrel: Vertical Foregrip","Magazine: Extended Mag II"],
     "reasoning":"Iconic MW2/WZ1 AR. Low recoil makes it forgiving for new players."},
    {"weapon_name":"XMG","weapon_class":"LMG","game":"Warzone","play_style":"Support","tier":"A","confidence":0.66,
     "attachments":["Optic: Jason Armory 2X","Muzzle: Suppressor","Barrel: Reinforced Barrel","Underbarrel: Vertical Foregrip","Magazine: Fast Mag I","Rear Grip: Commando Grip","Stock: Combat Stock","Fire Mods: Recoil Springs"],
     "reasoning":"Dual-wieldable LMG with massive mag. Suppression machine for team play."},
    {"weapon_name":"PPSH-41","weapon_class":"SMG","game":"Warzone","play_style":"Hip Fire","tier":"A","confidence":0.66,
     "attachments":["Optic: Kepler Microflex","Muzzle: Compensator","Barrel: Long Barrel","Underbarrel: Vertical Foregrip","Magazine: Extended Mag II"],
     "reasoning":"WW2-era SMG with very high fire rate. Best hipfire drum SMG in its class."},
    {"weapon_name":"LC10","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"A","confidence":0.65,
     "attachments":["Muzzle: Compensator","Barrel: Long Barrel","Underbarrel: Ranger Foregrip","Magazine: Extended Mag II","Rear Grip: Commando Grip"],
     "reasoning":"Reliable CW SMG. Low recoil and solid range make it easy to use."},
    {"weapon_name":"Goblin MK 2","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.65,
     "attachments":["Optic: Willis 3X","Muzzle: Compensator","Barrel: Gain-Twist Barrel","Underbarrel: Vertical Foregrip","Magazine: Extended Mag II"],
     "reasoning":"Fast-fire AR from BO6. Punches above its weight at medium range."},
    {"weapon_name":"GPR 91","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.65,
     "attachments":["Optic: Volzhskiy Reflex","Muzzle: Compensator","Barrel: Reinforced Barrel","Underbarrel: Vertical Foregrip","Magazine: Extended Mag II"],
     "reasoning":"Stable BO6 AR. Consistent at range with manageable recoil pattern."},
    {"weapon_name":"CR-56 AMAX","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.65,
     "attachments":["Optic: Volzhskiy Reflex","Muzzle: Compensator","Barrel: Gain-Twist Barrel","Underbarrel: Vertical Foregrip","Magazine: Extended Mag II"],
     "reasoning":"High-damage AR from MW. 7.62 rounds deal more per-shot damage than most ARs."},
    {"weapon_name":"Static-HV","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"A","confidence":0.65,
     "attachments":["Optic: Slate Reflector","Muzzle: Quartermaster Suppressor","Barrel: Auger 840 Light Barrel","Underbarrel: DR-6 Handstop","Stock: Spry 34 Light Stock"],
     "reasoning":"High-velocity SMG with suppressor. Strong at short-to-mid range."},
    {"weapon_name":"LW3A1 Frostline","weapon_class":"Sniper","game":"Warzone","play_style":"Sniper","tier":"A","confidence":0.65,
     "attachments":["Barrel: Reinforced Barrel","Stock: Heavy Stock","Laser: Target Laser","Comb: Quickdraw Riser","Stock Pad: Ranger Pad"],
     "reasoning":"BO6 bolt-action sniper. Solid alternative when BO7 snipers aren't available."},
    {"weapon_name":"LR 7.62","weapon_class":"Sniper","game":"Warzone","play_style":"Sniper","tier":"A","confidence":0.65,
     "attachments":["Barrel: Reinforced Barrel","Rear Grip: Quickdraw Grip","Stock: Heavy Stock","Laser: Target Laser","Fire Mods: Rapid Fire"],
     "reasoning":"Semi-auto long-range sniper. Good for follow-up shots on armored targets."},
    {"weapon_name":"Merrick 556","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.64,
     "attachments":["Optic: Willis 3X","Muzzle: Compensator","Barrel: Gain-Twist Barrel","Underbarrel: Vertical Foregrip","Magazine: Extended Mag II"],
     "reasoning":"Balanced AR with above-average bullet speed. Gets the job done."},
    {"weapon_name":"AK-74","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.64,
     "attachments":["Muzzle: Compensator","Underbarrel: Ranger Foregrip","Magazine: Extended Mag II","Rear Grip: Quickdraw Grip","Stock: Infiltrator Stock"],
     "reasoning":"Classic AK with manageable recoil. Slightly outclassed but remains reliable."},
    {"weapon_name":"AS VAL","weapon_class":"AR","game":"Warzone","play_style":"Aggressive","tier":"A","confidence":0.64,
     "attachments":["Barrel: Suppressed Gain-Twist Barrel","Underbarrel: Vertical Foregrip","Magazine: Extended Mag II","Stock: Balanced Stock","Fire Mods: Recoil Springs"],
     "reasoning":"Built-in suppressor and fast fire rate. Best used aggressively in tight spaces."},
    {"weapon_name":"Dresden 9mm","weapon_class":"SMG","game":"Warzone","play_style":"Aggressive","tier":"A","confidence":0.64,
     "attachments":["Muzzle: Compensator","Barrel: Long Barrel","Magazine: Extended Mag II","Rear Grip: Ergonomic Grip","Stock: No Stock"],
     "reasoning":"Lightweight no-stock SMG. Maximum mobility for rush-focused players."},
    {"weapon_name":"Krig C","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.63,
     "attachments":["Optic: Jason Armory 2X","Muzzle: Compensator","Barrel: Gain-Twist Barrel","Underbarrel: Vertical Foregrip","Magazine: Extended Mag II"],
     "reasoning":"Consistent AR from BO6. Reliable but lacks standout attributes."},
    {"weapon_name":"Model L","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.63,
     "attachments":["Optic: Jason Armory 2X","Muzzle: Compensator","Barrel: Gain-Twist Barrel","Underbarrel: Vertical Foregrip","Magazine: Extended Mag II"],
     "reasoning":"Modern rifle with clean iron sights. Works best with an optic at range."},
    {"weapon_name":"DM-10","weapon_class":"Marksman","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.63,
     "attachments":["Optic: Willis 3X","Muzzle: Ported Compensator","Barrel: Reinforced Barrel","Magazine: Extended Mag II","Stock: Buffer Weight Stock"],
     "reasoning":"Semi-auto battle rifle. Each shot deals high damage; skilled players get good value."},
    {"weapon_name":"TR2","weapon_class":"Marksman","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.63,
     "attachments":["Optic: Willis 3X","Muzzle: Ported Compensator","Barrel: Gain-Twist Barrel","Underbarrel: Vertical Foregrip","Magazine: Extended Mag II"],
     "reasoning":"Semi-auto rifle with fast fire rate. Good bridge between AR and sniper play styles."},
    {"weapon_name":"SWAT 5.56","weapon_class":"Marksman","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.63,
     "attachments":["Optic: Volzhskiy Reflex","Muzzle: Ported Compensator","Underbarrel: Vertical Foregrip","Magazine: Full-Auto Extended Mag","Fire Mods: SWAT 5.56 Grau Conversion"],
     "reasoning":"Full-auto conversion makes it an AR-SMG hybrid. Interesting niche build."},
    {"weapon_name":"C9","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"A","confidence":0.63,
     "attachments":["Barrel: Long Barrel","Underbarrel: Vertical Foregrip","Magazine: Extended Mag II","Rear Grip: Ergonomic Grip","Stock: Balanced Stock"],
     "reasoning":"Clean CW SMG. Simple but effective close-range option."},
    {"weapon_name":"Sirin 9mm","weapon_class":"SMG","game":"Warzone","play_style":"Hip Fire","tier":"A","confidence":0.62,
     "attachments":["Optic: Iron Sight","Muzzle: Suppressor","Barrel: Long Barrel","Underbarrel: Vertical Foregrip","Magazine: Extended Mag I"],
     "reasoning":"Compact suppressed SMG. Good secondary when stealth is a priority."},
    {"weapon_name":"Cypher 091","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.62,
     "attachments":["Optic: Willis 3X","Muzzle: Compensator","Barrel: Gain-Twist Barrel","Underbarrel: Vertical Foregrip","Magazine: Extended Mag II"],
     "reasoning":"Mid-tier AR. Works fine but has no edge over the higher-tier options."},
    {"weapon_name":"Essex Model 07","weapon_class":"Marksman","game":"Warzone","play_style":"Long Range","tier":"A","confidence":0.62,
     "attachments":["Optic: Willis 3X","Muzzle: Ported Compensator","Barrel: Long Barrel","Underbarrel: Weighted Handguard","Magazine: Stripper Clip"],
     "reasoning":"Bolt-action marksman rifle. Unique stripper clip reload adds a tactical element."},
    {"weapon_name":"Tanto .22","weapon_class":"SMG","game":"Warzone","play_style":"Hip Fire","tier":"A","confidence":0.62,
     "attachments":["Muzzle: Compensator","Barrel: Reinforced Barrel","Magazine: Extended Mag I","Stock: No Stock","Fire Mods: .22 WMR Overpressured"],
     "reasoning":"High-calibre .22 conversion. Niche pick but surprisingly strong at close range."},
    {"weapon_name":"Olympia","weapon_class":"Shotgun","game":"Warzone","play_style":"Close Range","tier":"A","confidence":0.62,
     "attachments":["Barrel: Short Barrel","Stock: Cut-Off Stock"],
     "reasoning":"Two-shot break-action. One-shot potential but extreme commitment to close quarters."},
    # ══════════════════════════════════════════════════════
    # B TIER (Unrated / Below Meta)
    # ══════════════════════════════════════════════════════
    {"weapon_name":"HDR","weapon_class":"Sniper","game":"Warzone","play_style":"Sniper","tier":"A","confidence":0.68,
     "attachments":["Muzzle: Monolithic Suppressor","Barrel: Gain-Twist Barrel","Underbarrel: Lightweight Bipod","Rear Grip: Quickdraw Grip","Fire Mods: 108MM Overpressured"],
     "reasoning":"Classic WZ1 sniper. Still listed as Acceptable — works at range but slower than BO7 options."},
    {"weapon_name":"Rival-9","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"B","confidence":0.60,
     "attachments":["Muzzle: Shadowstrike Suppressor S","Underbarrel: XRK Edge BW-4 Handstop","Magazine: 40 Round Mag","Rear Grip: Rival Vice Assault Grip","Stock: EXF Close Quarters Assault Stock"],
     "reasoning":"Was meta in its season. Now outclassed by BO7 SMGs."},
    {"weapon_name":"Holger 26","weapon_class":"LMG","game":"Warzone","play_style":"Support","tier":"B","confidence":0.60,
     "attachments":["Optic: Corio Eagleseye 2.5X","Muzzle: VT-7 Spiritfire Suppressor","Barrel: Holger Factory Barrel","Underbarrel: Bruen Heavy Support Grip","Stock: Ascent Lord Stock"],
     "reasoning":"MW3 era LMG, now replaced by MK.78. Still usable for budget loadouts."},
    {"weapon_name":"RAM-7","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"B","confidence":0.58,
     "attachments":["Muzzle: Casus Brake","Barrel: Cronen Headwind Long Barrel","Underbarrel: Bruen Heavy Support Grip","Magazine: 60 Round Drum","Stock: HVS 3.4 Pad"],
     "reasoning":"Legacy MW3 AR. Outclassed by every BO7 AR."},
    {"weapon_name":"MCW","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"B","confidence":0.58,
     "attachments":["Conversion Kit: JAK Raven Kit","Optic: JAK Glassless Optic","Muzzle: Quartermaster Suppressor","Underbarrel: Paracord Grip","Magazine: 40 Round Mag"],
     "reasoning":"MW3 AR that needs a conversion kit to stay relevant. Outdone by BO7 options."},
    {"weapon_name":"Striker","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"B","confidence":0.58,
     "attachments":["Muzzle: Quartermaster Suppressor","Underbarrel: Paracord Grip","Magazine: 48 Round Mag","Stock: Lachmann MK2 Light Stock","Ammunition: .45 Auto High Grain Rounds"],
     "reasoning":"MW3 SMG past its prime. Solid fundamentals but outclassed by newer options."},
    {"weapon_name":"Pulemyot 762","weapon_class":"LMG","game":"Warzone","play_style":"Support","tier":"B","confidence":0.57,
     "attachments":["Optic: JAK Glassless Optic","Muzzle: Quartermaster Suppressor","Barrel: ST Pyro Heavy Barrel","Stock: Ivanov Wood Stock","Ammunition: 7.62x54mmR High Grain Rounds"],
     "reasoning":"Russian LMG with high damage per shot. Slow fire rate limits its viability."},
    {"weapon_name":"MTZ-556","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"B","confidence":0.57,
     "attachments":["Optic: JAK Glassless Optic","Muzzle: VT-7 Spiritfire Suppressor","Barrel: MTZ Drifter Heavy Long Barrel","Underbarrel: Bruen Heavy Support Grip","Magazine: 50 Round Drum"],
     "reasoning":"MW3 AR that was meta once. Still functional at range but outdated."},
    {"weapon_name":"Holger 556","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"B","confidence":0.57,
     "attachments":["Optic: JAK Glassless Optic","Muzzle: VT-7 Spiritfire Suppressor","Barrel: Chrios-6 Match","Underbarrel: Bruen Heavy Support Grip","Magazine: 40 Round Mag"],
     "reasoning":"Old MW3 AR. Has been power-crept by BO7 weapons."},
    {"weapon_name":"STG44","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"B","confidence":0.57,
     "attachments":["Optic: JAK Glassless Optic","Muzzle: Quartermaster Suppressor","Barrel: Heinrichter C70 Long Barrel","Magazine: 50 Round Drum","Stock: DR79 Combo Stock"],
     "reasoning":"WW2 rifle still in Warzone. Novelty pick at best in the current meta."},
    {"weapon_name":"DG-56","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"B","confidence":0.57,
     "attachments":["Optic: Corio Eagleseye 2.5X","Muzzle: VT-7 Spiritfire Suppressor","Barrel: DG-56 LS18 Barrel","Underbarrel: Kimura RYN-03 Vertical Grip","Magazine: 60 Round Mag"],
     "reasoning":"BO6 AR that's been power-crept. Still viable for BO6 purists."},
    {"weapon_name":"BAL-27","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"B","confidence":0.57,
     "attachments":["Optic: JAK Glassless Optic","Muzzle: Quartermaster Suppressor","Barrel: Noctkill Long Barrel","Underbarrel: Bruen Heavy Support Grip","Magazine: 60 Round Mag"],
     "reasoning":"AW-era AR. High fire rate but damage falls off quickly at range."},
    {"weapon_name":"SVA 545","weapon_class":"AR","game":"Warzone","play_style":"Long Range","tier":"B","confidence":0.57,
     "attachments":["Optic: Corio Eagleseye 2.5X","Muzzle: VT-7 Spiritfire Suppressor","Barrel: STV Precision Barrel","Magazine: 60 Round Mag","Ammunition: 5.45 High Grain Rounds"],
     "reasoning":"MW3 AR with burst-fire potential. Inconsistent in full-auto mode."},
    {"weapon_name":"Kastov LSW","weapon_class":"LMG","game":"Warzone","play_style":"Support","tier":"B","confidence":0.56,
     "attachments":["Optic: JAK Glassless Optic","Muzzle: Quartermaster Suppressor","Barrel: Elevator D20 Long Barrel","Underbarrel: Paracord Grip","Stock: Spetsnaz S15 Stock"],
     "reasoning":"MW3 LMG. Slower than the current meta but has a large magazine."},
    {"weapon_name":"TAQ Eradicator","weapon_class":"LMG","game":"Warzone","play_style":"Support","tier":"B","confidence":0.56,
     "attachments":["Optic: JAK Glassless Optic","Muzzle: Quartermaster Suppressor","Barrel: Conquer-70 Long Barrel","Underbarrel: Paracord Grip","Stock: Tacverte Core Stock"],
     "reasoning":"MW2 LMG past its prime. Outperformed by every current-gen LMG."},
    {"weapon_name":"DG-58 LSW","weapon_class":"LMG","game":"Warzone","play_style":"Support","tier":"B","confidence":0.56,
     "attachments":["Muzzle: Casus Brake","Barrel: Wudi Long Barrel","Underbarrel: Bruen Heavy Support Grip","Rear Grip: Varanus Steady Grip","Stock: Recoil Reduction Buttplate"],
     "reasoning":"BO6 LMG that gets the job done but can't compete with MK.78 or Sokol."},
    {"weapon_name":"Bruen MK9","weapon_class":"LMG","game":"Warzone","play_style":"Support","tier":"B","confidence":0.56,
     "attachments":["Optic: JAK Glassless Optic","Muzzle: Zehmn35 Compensated Flash Hider","Barrel: 23\" XRK Horizon V2","Underbarrel: Bruen Heavy Support Grip","Magazine: 60 Round Mag"],
     "reasoning":"Iconic MW2 LMG. Outclassed by BO7 options but still a nostalgia pick."},
    {"weapon_name":"TAQ Evolvere","weapon_class":"LMG","game":"Warzone","play_style":"Support","tier":"B","confidence":0.56,
     "attachments":["Optic: Corio Eagleseye 2.5X","Muzzle: Zehmn35 Compensated Flash Hider","Barrel: Eviction 762 Heavy Barrel","Magazine: 100 Round 556 Belt","Stock: Rampart Heavy Stock"],
     "reasoning":"100-round belt LMG. Mobile suppression but lacks the damage to compete."},
    {"weapon_name":"Lockwood 300","weapon_class":"Shotgun","game":"Warzone","play_style":"Close Range","tier":"B","confidence":0.56,
     "attachments":["Muzzle: Bryson Series XII Choke","Barrel: Matuzek 812 Barrel","Underbarrel: Bruen Bastion Angled Grip","Stock: Heist Stock Mod","Trigger Action: Maelstrom Dual Trigger"],
     "reasoning":"Double-barrel shotgun. Dual-trigger conversion is lethal but has a steep learning curve."},
    {"weapon_name":"Reclaimer 18","weapon_class":"Shotgun","game":"Warzone","play_style":"Close Range","tier":"B","confidence":0.56,
     "attachments":["Muzzle: Bryson Choke","Barrel: Ironbrand Long Barrel","Underbarrel: Bruen Bastion Angled Grip","Stock: No Stock","Laser: Kimura RYL33 Laser"],
     "reasoning":"Semi-auto shotgun. Consistent but doesn't hit hard enough for the current meta."},
    {"weapon_name":"Haymaker","weapon_class":"Shotgun","game":"Warzone","play_style":"Close Range","tier":"B","confidence":0.56,
     "attachments":["Muzzle: Bryson Choke","Barrel: Imperator Long Barrel","Underbarrel: Bruen Bastion Angled Grip","Magazine: 20 Round Drum","Stock: No Stock Mod"],
     "reasoning":"Auto-shotgun with large drum. Aggressive but inconsistent against armored targets."},
    {"weapon_name":"Lockwood 680","weapon_class":"Shotgun","game":"Warzone","play_style":"Close Range","tier":"B","confidence":0.56,
     "attachments":["Muzzle: Crown Breaker Choke","Barrel: Lockwood Defender Heavy Long Barrel","Underbarrel: Bruen Bastion Angled Grip","Stock: Sawed Off Mod","Bolt: Express Light Bolt"],
     "reasoning":"Pump-action with sawed-off for mobility. One-shot capable but inconsistent."},
    {"weapon_name":"ASG-89","weapon_class":"Shotgun","game":"Warzone","play_style":"Close Range","tier":"B","confidence":0.55,
     "attachments":["Muzzle: Full Choke","Barrel: Reinforced Barrel","Magazine: Extended Mag II","Laser: Target Laser","Fire Mods: Recoil Springs"],
     "reasoning":"Semi-auto shotgun. Functional but not a top choice for any situation."},
    {"weapon_name":"Marine SP","weapon_class":"Shotgun","game":"Warzone","play_style":"Hip Fire","tier":"B","confidence":0.55,
     "attachments":["Optic: Kepler Red Dot","Muzzle: Modified Choke","Barrel: Reinforced Barrel","Underbarrel: Ranger Foregrip","Stock: Quickdraw Stock","Laser: Target Laser","Fire Mods: Rapid Fire"],
     "reasoning":"Rapid-fire shotgun. Hipfire and rapid fire combo is fun but not meta."},
    {"weapon_name":"Maelstrom","weapon_class":"Shotgun","game":"Warzone","play_style":"Close Range","tier":"B","confidence":0.55,
     "attachments":["Muzzle: Full Choke","Underbarrel: Vertical Foregrip","Magazine: Extended Mag II","Laser: Steady Aim Laser","Fire Mods: 12 Gauge Dragon's Breath"],
     "reasoning":"Dragon's Breath rounds add a fire damage effect. More gimmick than competitive tool."},
    {"weapon_name":"HRM-9","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"B","confidence":0.58,
     "attachments":["Muzzle: Zehmn35 Compensated Flash Hider","Underbarrel: DR-6 Handstop","Magazine: 50 Round Drum","Rear Grip: PCS-90 Assault Grip","Stock: Folding Stock"],
     "reasoning":"MW3 SMG that had its time in the sun. Now firmly in the legacy tier."},
    {"weapon_name":"Striker 9","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"B","confidence":0.58,
     "attachments":["Muzzle: Zehmn35 Compensated Flash Hider","Barrel: Striker Recon Long Barrel","Underbarrel: DR-6 Handstop","Magazine: 50 Round Mag","Stock: Striker Factory Stock"],
     "reasoning":"MW3 SMG with good range. Outclassed by BO7 alternatives."},
    {"weapon_name":"WSP Swarm","weapon_class":"SMG","game":"Warzone","play_style":"Hip Fire","tier":"B","confidence":0.57,
     "attachments":["Muzzle: Shadowstrike Suppressor S","Barrel: WSP Reckless-90 Long Barrel","Underbarrel: Bruen Heavy Support Grip","Magazine: 50 Round Mag","Stock: FSS Fortress Heavy Stock"],
     "reasoning":"Full-auto hipfire monster. Niche pick for players who never ADS."},
    {"weapon_name":"WSP-9","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"B","confidence":0.57,
     "attachments":["Optic: MK. 3 Reflector","Muzzle: Zehmn35 Compensated Flash Hider","Barrel: WSP Reckless-90 Long Barrel","Magazine: 50 Round Mag","Stock: WSP Classics Factory Stock"],
     "reasoning":"MW3 budget SMG. Outclassed by everything from BO7."},
    {"weapon_name":"AMR9","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"B","confidence":0.57,
     "attachments":["Optic: JAK Glassless Optic","Muzzle: Zehmn35 Compensated Flash Hider","Underbarrel: XRK Edge BW-4 Handstop","Magazine: 50 Round Mag","Stock: DAV15 Light Tactical Stock"],
     "reasoning":"Compact SMG from MW3. Decent mobility but below-average damage output."},
    {"weapon_name":"RAM-9","weapon_class":"SMG","game":"Warzone","play_style":"Aggressive","tier":"B","confidence":0.57,
     "attachments":["Muzzle: Sonic Suppressor S","Underbarrel: DR-6 Handstop","Magazine: 50 Round Mag","Rear Grip: Retort 90 Grip Tape","Stock: Motion-TAC Pad"],
     "reasoning":"Fast-handling SMG. Was strong in MW3 Warzone but not the BO7 meta."},
    {"weapon_name":"FJX Horus","weapon_class":"SMG","game":"Warzone","play_style":"Hip Fire","tier":"B","confidence":0.56,
     "attachments":["Muzzle: Zehmn35 Compensated Flash Hider","Barrel: SYN9 Long Barrel","Underbarrel: DR-6 Handstop","Magazine: 48 Round Mag","Ammunition: 9MM High Grain Rounds"],
     "reasoning":"Fast-fire PDW. Hipfire niche, but outclassed for ADS gameplay."},
    {"weapon_name":"SOA Subverter","weapon_class":"Marksman","game":"Warzone","play_style":"Long Range","tier":"B","confidence":0.57,
     "attachments":["Optic: JAK Glassless Optic","Muzzle: Casus Brake L","Barrel: Dozer-90 Long Barrel","Underbarrel: Bruen Heavy Support Grip","Magazine: 50 Round Drum"],
     "reasoning":"MW3 battle rifle. High damage per shot but slow fire rate and heavy recoil."},
    {"weapon_name":"BAS-B","weapon_class":"Marksman","game":"Warzone","play_style":"Long Range","tier":"B","confidence":0.57,
     "attachments":["Optic: Corio Eagleseye 2.5X","Muzzle: VT-7 Spiritfire Suppressor L","Barrel: Bruen Venom Long Barrel","Magazine: 45 Round Mag","Stock: Ravage-20 Heavy Stock"],
     "reasoning":"MW3 battle rifle with high bullet velocity. Outdated but still functional."},
    {"weapon_name":"MTZ Interceptor","weapon_class":"Marksman","game":"Warzone","play_style":"Long Range","tier":"B","confidence":0.57,
     "attachments":["Optic: Corio Eagleseye 2.5X","Muzzle: VT-7 Spiritfire Suppressor L","Barrel: MTZ Blackthorn Barrel","Underbarrel: Bruen Heavy Support Grip","Magazine: 20 Round Mag"],
     "reasoning":"Slow-fire marksman rifle. High damage ceiling but punishing if you miss."},
    {"weapon_name":"MTZ-762","weapon_class":"Marksman","game":"Warzone","play_style":"Long Range","tier":"B","confidence":0.57,
     "attachments":["Optic: Corio Eagleseye 2.5X","Muzzle: Zehmn35 Compensated Flash Hider","Barrel: MTZ-Precision Blackthorn Barrel","Magazine: 30 Round Mag","Stock: EXF Close Quarters Assault Stock"],
     "reasoning":"Semi-auto battle rifle. Chunky damage but recoil limits its effectiveness."},
    {"weapon_name":"DTIR 30-06","weapon_class":"Marksman","game":"Warzone","play_style":"Sniper","tier":"B","confidence":0.56,
     "attachments":["Optic: JAK Glassless Optic","Muzzle: Quartermaster Suppressor","Barrel: EXTND-10 Long Barrel","Magazine: 40 Round Mag","Stock: Rifleman 200 Stock"],
     "reasoning":"Bolt-action marksman. Niche between sniper and battle rifle."},
    {"weapon_name":"STB 556","weapon_class":"AR","game":"Warzone","play_style":"Lowest Recoil","tier":"B","confidence":0.56,
     "attachments":["Optic: Nydar Model 2023","Muzzle: JAK BFB (No Recoil)","Barrel: FTAC FB20","Underbarrel: Bruen Heavy Support Grip","Magazine: 42 Round Mag"],
     "reasoning":"Best recoil control in the game with JAK BFB, but damage is too low for meta play."},
    {"weapon_name":"BP50","weapon_class":"AR","game":"Warzone","play_style":"Aggressive","tier":"B","confidence":0.56,
     "attachments":["Conversion Kit: JAK Revenger Kit","Muzzle: Quartermaster Suppressor","Rear Grip: CCG-TAC Tape","Laser: Kimura RYL33 Laser","Ammunition: 5.56 NATO High Grain Rounds"],
     "reasoning":"High fire rate AR with conversion. Overwhelmed at range by BO7 ARs."},
    {"weapon_name":"Renetti","weapon_class":"Pistol","game":"Warzone","play_style":"Close Range","tier":"B","confidence":0.58,
     "attachments":["Barrel: MLX Short Competition Barrel","Magazine: 50 Round Drum","Rear Grip: Akimbo Renetti","Laser: XTEN Sidearm-L400","Trigger Action: Bruen Express"],
     "reasoning":"Akimbo pistols with drum mags. Fun close-range pick but not competitive."},
    {"weapon_name":"TYR","weapon_class":"Pistol","game":"Warzone","play_style":"Close Range","tier":"B","confidence":0.57,
     "attachments":["Barrel: ZIU-16 Heavy Long Barrel","Rear Grip: Akimbo TYR","Laser: XTEN Sidearm-L400","Ammunition: 12.7x55mm Snake Shot","Trigger Action: Ullr's Fury"],
     "reasoning":"Akimbo .50 cal pistols with snake shot. Shotgun-like pellet spread at close range."},
    {"weapon_name":"COR-45","weapon_class":"Pistol","game":"Warzone","play_style":"Close Range","tier":"B","confidence":0.57,
     "attachments":["Conversion Kit: XRK IP-V2 Conversion Kit","Muzzle: Sonic Suppressor XS","Magazine: 40 Round Drum","Rear Grip: Granular Grip","Stock: XRK Dynamic Precision Stock"],
     "reasoning":"Full-auto pistol with conversion kit. Budget SMG in a secondary slot."},
    {"weapon_name":"MORS","weapon_class":"Sniper","game":"Warzone","play_style":"Sniper","tier":"B","confidence":0.58,
     "attachments":["Optic: MCPR-300 9.5X","Barrel: Tonne Heavy Barrel","Stock: Icarus Light Stock","Ammunition: HVP Anti-Materiel Slug","Bolt: Quick Bolt"],
     "reasoning":"BO6 rail gun-style sniper. One-shot on full armor but extremely slow ADS."},
    {"weapon_name":"KATT-AMR","weapon_class":"Sniper","game":"Warzone","play_style":"Sniper","tier":"B","confidence":0.57,
     "attachments":["Muzzle: Sonic Suppressor XL","Barrel: Zang-34 Barrel","Stock: Tactical Stock Pad","Laser: SL Razorhawk Laser Light","Ammunition: .50 Cal High Velocity"],
     "reasoning":"Anti-materiel sniper. High one-shot potential but slowest ADS in the game."},
    {"weapon_name":"XRK Stalker","weapon_class":"Sniper","game":"Warzone","play_style":"Sniper","tier":"B","confidence":0.57,
     "attachments":["Muzzle: VT-7 Spiritfire Suppressor XL","Barrel: Fission 60 Barrel","Stock: Helix LV Light Stock","Laser: SL Razorhawk Laser Light","Ammunition: .50 Cal High Grain Rounds"],
     "reasoning":"Tactical sniper with good handling. Outclassed by BO7 snipers at range."},
    {"weapon_name":"SVD","weapon_class":"Sniper","game":"Warzone","play_style":"Sniper","tier":"B","confidence":0.55,
     "attachments":["Muzzle: Suppressor","Barrel: Reinforced Barrel","Underbarrel: Precision Handguard","Laser: Target Laser","Fire Mods: Recoil Springs"],
     "reasoning":"Soviet semi-auto sniper. Consistent fire rate but lacks one-shot power."},
    {"weapon_name":"AMR Mod 4","weapon_class":"Sniper","game":"Warzone","play_style":"Sniper","tier":"B","confidence":0.55,
     "attachments":["Muzzle: Muzzle Brake","Barrel: Reinforced Barrel","Magazine: Fast Mag I","Rear Grip: Quickdraw Grip","Laser: Target Laser","Fire Mods: Rapid Fire","Comb: Heavy Riser","Stock Pad: Precision Pad"],
     "reasoning":"Legacy sniper. Too many attachments needed to make it viable compared to newer options."},
    {"weapon_name":"Crossbow","weapon_class":"Marksman","game":"Warzone","play_style":"Sniper","tier":"B","confidence":0.50,
     "attachments":["Optic: Corio Eagleseye 2.5X","Underbarrel: FTAC Ripper 56","Cable: 28-Strand Cable","Bolt: Blastcap 20\" Bolts","Arms: SO Momenti"],
     "reasoning":"Niche crossbow. Fun to use but limited viability against armored targets in BR."},
    {"weapon_name":"D1.3 Sector","weapon_class":"SMG","game":"Warzone","play_style":"Close Range","tier":"B","confidence":0.50,
     "attachments":["Barrel: Long Barrel","Underbarrel: Crossbar","Magazine: Explosive Blades","Stock: Overclocked Stock"],
     "reasoning":"Unique special-ammo SMG. Interesting gimmick but inconsistent damage output."},
]


def scrape() -> list[dict]:
    try:
        headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}
        resp = requests.get(WZHUB_URL, headers=headers, timeout=15)
        resp.raise_for_status()
        print(f"[wzhub] live fetch succeeded ({len(resp.text)} bytes) — using embedded dataset")
    except Exception as e:
        print(f"[wzhub] live fetch failed: {e} — using embedded dataset")

    # Website sources only carry the top three tiers (Absolute Meta / Meta
    # / A). B and F tier weapons are omitted — the app only surfaces the
    # genuinely competitive picks from website sources.
    ALLOWED_TIERS = ("Absolute Meta", "Meta", "A")

    result = []
    dropped = 0
    for b in WARZONE_BUILDS:
        if b["tier"] not in ALLOWED_TIERS:
            dropped += 1
            continue
        # In the new schema, play_style identifies the source ("WZ Hub")
        # and weapon_dominancy holds the old style label (Long Range, etc.)
        result.append({
            **b,
            "play_style": "WZ Hub",
            "weapon_dominancy": b.get("play_style"),
            "title": f"{b['weapon_name']} {b['tier']} build",
            "text": (f"Weapon: {b['weapon_name']}\nClass: {b['weapon_class']}\n"
                     f"Tier: {b['tier']}\nDominancy: {b.get('play_style')}\n"
                     f"Attachments: {', '.join(b['attachments'])}\n"
                     f"Reasoning: {b['reasoning']}"),
            "source_type": "website",
            "source_url": WZHUB_URL,
            "source_title": "wzhub.gg — Warzone Meta Season 3",
        })
    print(f"[wzhub] returning {len(result)} builds (dropped {dropped} below-A-tier)")
    return result
